### ISSUE TITLE
Migration to v10

### ISSUE THREAD

**Issue by damendieta** [techspawn/warehouse_stock_restrictions#1]
Hi, I'm migrating this module to v10 on this fork:

damendieta/warehouse_stock_restrictions on branch 10.0

Would you like me to make a PR?

Daniel.

**Comment by techspawn** [comment]
Sure

**Comment by damendieta** [comment]
Could you please create a 10.0 branch so I can make a PR against it.

Thanks.

**Comment by techspawn** [comment]
Created branch 10.0  
Feel free to send PR. let me know if need any more help

**Comment by damendieta** [comment]
PR done #2

**Comment by techspawn** [comment]
Accepted :)
